test: &TEST
  adapter: postgresql
  encoding: utf8
  database: dumbfound_test
  pool: 5
  username:
  password:

development:
  adapter: postgresql
  encoding: utf8
  database: dumbfound_development
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: dumbfound_production
  pool: 5
  username:
  password:
